# Generated by Django 4.2.3 on 2023-07-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='testApp/static/profileImage/default.png', upload_to='testApp/static/profileImage'),
        ),
    ]
