# Generated by Django 4.2.3 on 2023-07-30 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testApp', '0003_alter_profile_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise_Day',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='exercise_day', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('mon', models.BooleanField(default=True)),
                ('tue', models.BooleanField(default=True)),
                ('wed', models.BooleanField(default=True)),
                ('thu', models.BooleanField(default=True)),
                ('fri', models.BooleanField(default=True)),
                ('sat', models.BooleanField(default=True)),
                ('sun', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Completed_Dates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('completed', models.BooleanField()),
                ('date', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completed_dates', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
