# Generated by Django 4.2.3 on 2023-07-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='testApp/image/profileImage/default.png', upload_to='testApp/image/profileImage'),
        ),
    ]
