# Generated by Django 4.2.3 on 2023-07-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0004_exercise_day_completed_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='streak',
            field=models.IntegerField(default=0),
        ),
    ]
